import os

SCAN_RECORDINGS_FOLDER = os.environ["SCAN_RECORDINGS_FOLDER"]
OUTPUT_FOLDER = os.environ["BIRDNET_OUTPUT_FOLDER"]
SNIPPETS_FOLDER = f"{OUTPUT_FOLDER}/snippets"
RESULTS_FOLDER = f"{OUTPUT_FOLDER}/results"
NOCMIG_SLACK_WEBHOOK_URL = os.environ["NOCMIG_SLACK_WEBHOOK_URL"]
