import os

SCAN_RECORDINGS_FOLDER = os.environ["SCAN_RECORDINGS_FOLDER"]
OUTPUT_FOLDER = os.environ["OUTPUT_FOLDER"]
SLACK_BOT_TOKEN = os.environ["SLACK_BOT_TOKEN"]
SLACK_CHANNEL_ID = os.environ["SLACK_CHANNEL_ID"]

SNIPPETS_FOLDER = f"{OUTPUT_FOLDER}/snippets"
RESULTS_FOLDER = f"{OUTPUT_FOLDER}/results"

